name: Draft

on:
  push:
    branches:
      - main

jobs:

  draft:
    name: Draft
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5.18.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
